# Generated by Django 6.0 on 2025-12-17 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskcomment',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
