# Generated by Django 6.0 on 2025-12-17 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_task_taskcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskcomment',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
